/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.googlesignin

import android.os.CancellationSignal
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import org.appcelerator.kroll.KrollDict
import org.appcelerator.kroll.KrollModule
import org.appcelerator.kroll.annotations.Kroll
import org.appcelerator.kroll.annotations.Kroll.method
import org.appcelerator.kroll.annotations.Kroll.module
import org.appcelerator.kroll.common.Log
import org.appcelerator.kroll.common.TiMessenger
import org.appcelerator.titanium.TiApplication


@module(name = "Googlesignin", id = "ti.googlesignin")
class GooglesigninModule : KrollModule() {
    var cancellationSignal: CancellationSignal? = null

    companion object {
        const val LCAT = "TiGoogleSignIn"
        @Kroll.constant val LOGIN_TYPE_DIALOG = "LOGIN_TYPE_DIALOG"
        @Kroll.constant val LOGIN_TYPE_SHEET = "LOGIN_TYPE_SHEET"

        @Kroll.constant val ERROR_TYPE_UNKNOWN = "ERROR_TYPE_UNKNOWN"
        @Kroll.constant val ERROR_TYPE_CONTEXT_MISSING = "ERROR_TYPE_CONTEXT_MISSING"
        @Kroll.constant val ERROR_TYPE_NO_CREDENTIAL = "ERROR_TYPE_NO_CREDENTIAL"
        @Kroll.constant val ERROR_TYPE_TOKEN_PARSING = "ERROR_TYPE_TOKEN_PARSING"
        @Kroll.constant val ERROR_TYPE_INTERRUPTED = "ERROR_TYPE_INTERRUPTED"
        @Kroll.constant val ERROR_TYPE_CANCELLED = "ERROR_TYPE_CANCELLED"
        @Kroll.constant val ERROR_TYPE_CONFIGURATION = "ERROR_TYPE_CONFIGURATION"
        @Kroll.constant val ERROR_TYPE_UNSUPPORTED = "ERROR_TYPE_UNSUPPORTED"
    }

    @method
    fun initialize(opts: KrollDict) {
        Log.d(LCAT, "=== Google Sign In Initialize ===")

        if (!opts.containsKeyAndNotNull("clientID")) {
            Log.e(LCAT, "Missing required \"clientID\" property!")
            return
        }

        val clientID = opts.getString("clientID")
        Log.d(LCAT, "Client ID: $clientID")
        TiCredentialManager.apiKey = clientID

        Log.d(LCAT, "Initialization complete")
    }

    @method
    fun cancel(): Boolean {
        Log.d(LCAT, "Cancel requested")
        cancellationSignal?.cancel()
        return cancellationSignal?.isCanceled ?: false
    }

    @method
    fun signIn(@Kroll.argument(optional = true)params: KrollDict?) {
        Log.d(LCAT, "=== Sign In Requested ===")

        // Log parameters if provided
        params?.let {
            Log.d(LCAT, "Parameters:")
            for (key in it.keys) {
                Log.d(LCAT, "  - $key: ${it.get(key)}")
            }
        }

        // Create cancellation signal here to pass further and to be controlled from JS side using this class itself.
        cancellationSignal = CancellationSignal()

        if (TiApplication.isUIThread()) {
            Log.d(LCAT, "Running on UI thread")
            TiCredentialManager.googleSignIn(this, params)
        } else {
            Log.d(LCAT, "Posting to UI thread")
            TiMessenger.postOnMain {
                TiCredentialManager.googleSignIn(this, params)
            }
        }
    }

    @method
    fun signOut() {
        Log.d(LCAT, "=== Sign Out Requested ===")
        TiCredentialManager.signOut(this)
    }

    fun fireLogoutEvent(success: Boolean = false, error: String = "") {
        Log.d(LCAT, "=== Logout Event ===")
        Log.d(LCAT, "Success: $success")
        if (error.isNotEmpty()) {
            Log.e(LCAT, "Error: $error")
        }

        val result = KrollDict()
        result["error"] = error
        result["success"] = success
        fireEvent("logout", result)
    }

    fun fireLoginEvent(
        credential: GoogleIdTokenCredential? = null,
        cancelled: Boolean = false,
        errorType: String = ERROR_TYPE_UNKNOWN,
        error: Exception? = null)
    {
        Log.d(LCAT, "=== Login Event ===")

        val event = KrollDict()

        if (credential == null) {
            val errorMessage = error?.localizedMessage ?: "Unknown error"
            event["error"] = errorMessage
            event["errorType"] = errorType

            // Log detalhado do erro
            Log.e(LCAT, "Google login FAILED:")
            Log.e(LCAT, "  - Error Type: $errorType")
            Log.e(LCAT, "  - Error Message: $errorMessage")
            Log.e(LCAT, "  - Cancelled: $cancelled")

            if (error != null) {
                Log.e(LCAT, "  - Exception Class: ${error.javaClass.name}")
                Log.e(LCAT, "  - Exception Message: ${error.message}")

                // Stack trace completo
                Log.e(LCAT, "  - Full Stack Trace:")
                error.stackTrace.forEach { element ->
                    Log.e(LCAT, "      at $element")
                }

                // Causa raiz
                error.cause?.let { cause ->
                    Log.e(LCAT, "  - Caused By: ${cause.javaClass.name}")
                    Log.e(LCAT, "    Message: ${cause.message}")
                    cause.stackTrace.take(5).forEach { element ->
                        Log.e(LCAT, "      at $element")
                    }
                }

                // Exceções suprimidas
                if (error.suppressed.isNotEmpty()) {
                    Log.e(LCAT, "  - Suppressed Exceptions:")
                    error.suppressed.forEach { suppressed ->
                        Log.e(LCAT, "    - ${suppressed.javaClass.name}: ${suppressed.message}")
                    }
                }
            } else {
                Log.e(LCAT, "  - No exception provided!")
            }
        } else {
            Log.d(LCAT, "Google login SUCCESSFUL!")
            Log.d(LCAT, "  - User ID (email): ${credential.id}")
            Log.d(LCAT, "  - Display Name: ${credential.displayName}")
            Log.d(LCAT, "  - Given Name: ${credential.givenName}")
            Log.d(LCAT, "  - Family Name: ${credential.familyName}")
            Log.d(LCAT, "  - Profile Picture: ${credential.profilePictureUri}")
            Log.d(LCAT, "  - ID Token length: ${credential.idToken.length}")
        }

        event["cancelled"] = cancelled
        event["success"] = credential != null
        event["user"] = credential?.let { parseUserCredentials(it) }

        fireEvent("login", event)
    }

    private fun parseUserCredentials(googleIdTokenCredential: GoogleIdTokenCredential): KrollDict {
        val user = KrollDict()

        googleIdTokenCredential.let {
            val auth = KrollDict()
            auth["idToken"] = it.idToken

            val profile = KrollDict()
            profile["familyName"] = it.familyName ?: ""
            profile["givenName"] = it.givenName ?: ""
            profile["name"] = it.displayName ?: ""
            profile["displayName"] = it.displayName ?: ""
            profile["email"] = it.id
            profile["image"] = it.profilePictureUri?.toString() ?: ""

            user["profile"] = profile
            user["authentication"] = auth
        }

        return user
    }
}